import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Provider from "./Provider";
import HeaderNavBar from "@/components/HeaderNavBar";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Provider>
          <HeaderNavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
